FROM python
COPY ./static /home/app/static/
COPY ./templates /home/app/templates/
COPY app.py /home/app/
COPY requirements.txt /home/app/
RUN pip install -r /home/app/requirements.txt
EXPOSE 5000
CMD python3 /home/app/app.py
FROM python
COPY ./static /home/app/static/
COPY ./templates /home/app/templates/
COPY app.py /home/app/
COPY requirements.txt /home/app/
RUN pip install -r /home/app/requirements.txt
EXPOSE 5000
CMD python3 /home/app/app.py
FROM python
COPY ./static /home/app/static/
COPY ./templates /home/app/templates/
COPY app.py /home/app/
COPY requirements.txt /home/app/
RUN pip install -r /home/app/requirements.txt
EXPOSE 5000
CMD python3 /home/app/app.py
FROM python
COPY ./static /home/app/static/
COPY ./templates /home/app/templates/
COPY app.py /home/app/
COPY requirements.txt /home/app/
RUN pip install -r /home/app/requirements.txt
EXPOSE 5000
CMD python3 /home/app/app.py
